#!/usr/bin/env bash

readonly ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
readonly HELPERS_DIR="$ROOT_DIR/helpers"
readonly PACKAGES_DIR="$ROOT_DIR/packages"

set -o errexit
set -o pipefail

. "$HELPERS_DIR/brew.sh"
. "$HELPERS_DIR/output.sh"
. "$HELPERS_DIR/package.sh"
. "$HELPERS_DIR/symlink.sh"

packages=()
if [ ! $# -eq 0 ]; then
  # Manually selected packages
  packages=$*
elif [[ -n "${GITPOD_WORKSPACE_ID}" ]]; then
  # Gitpod packages
  packages=(
    homebrew
    zsh
  )
elif [[ $(uname) == "Darwin" ]]; then
  # MacOS packages
  packages=(
    xcode
    homebrew
    macos
    git
    elixir
    node
    ruby
    tmux
    # vim -- one of the vimbundles keeps breaking
  )
fi

install_packages "${packages[@]}"
